# Generated by Django 5.0.4 on 2024-05-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
